/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/About': RouteRecordInfo<
      '/About',
      '/About',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/how-i-manage-my-blog': RouteRecordInfo<
      '/posts/how-i-manage-my-blog',
      '/posts/how-i-manage-my-blog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/how-to-use-codeceptjs': RouteRecordInfo<
      '/posts/how-to-use-codeceptjs',
      '/posts/how-to-use-codeceptjs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/[tag]': RouteRecordInfo<
      '/tags/[tag]',
      '/tags/:tag',
      { tag: ParamValue<true> },
      { tag: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'contents/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'contents/About.md': {
      routes:
        | '/About'
      views:
        | never
    }
    'contents/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'contents/posts/how-i-manage-my-blog.md': {
      routes:
        | '/posts/how-i-manage-my-blog'
      views:
        | never
    }
    'contents/posts/how-to-use-codeceptjs.md': {
      routes:
        | '/posts/how-to-use-codeceptjs'
      views:
        | never
    }
    'contents/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
    'contents/tags/[tag].md': {
      routes:
        | '/tags/[tag]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
